build_script:
  - msbuild DiscUtils.Core.sln /p:Configuration=Release /p:Platform="Any CPU" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  
on_success:
  - cmd: nuget pack Quamotion.DiscUtils.nuspec -Version %APPVEYOR_BUILD_VERSION%
  - ps: Push-AppveyorArtifact "Quamotion.DiscUtils.$($env:APPVEYOR_BUILD_VERSION).nupkg"